### ISSUE TITLE
Wees flexibler over naamgegevens?

### ISSUE THREAD

**Issue by rien333** [Regionaal-Archief-Rivierenland/ORI-XSD#36]
In praktijk is de naam van een persoon is lang niet altijd mooi opgesplitst in voornaam, achternaam, en tussenvoegsel. Bij de VNG hebben ze dit ingecalculeerd ([bron](https://raw.githubusercontent.com/VNG-Realisatie/ODS-Open-Raadsinformatie/master/docs/mini-ORI-API/openapi.yaml)): 

```yaml
NaamNatuurlijkPersoon:
      type: "object"
      description: "De naam van een natuurlijk persoon. Wanneer de naam bij het invullen niet \
      opgesplitst is in voornamen, tussenvoegsel en achternaam kan de naam ook in één keer worden geregistreerd in het veld volledigeNaam."
```
Misschien een goed idee om te zeggen dat ofwel een volledige naam, ofwel een achternaam verplicht is? Op dit moment verplichten we specifiek een achternaam, maar die is niet altijd met zekerheid te herleiden.
